import {} from './modules/getData.js'
import {} from './modules/photographers.js'
import {} from './modules/singlePhotographer.js'
import { filterData } from './modules/FilterMedia.js'
import {} from './modules/navigationGalery.js'
import {} from './modules/submitForm.js'
import {} from './factories/Photographer.js'
import {} from './factories/PhotographerPage.js'
import {} from './factories/PhotographerProfile.js'
window.filterData = filterData